import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { fontSize: 22, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  section: { margin: 10, padding: 15, border: '1pt solid #ccc', borderRadius: 8 },
  barcodeContainer: { marginTop: 40, alignItems: 'center' },
  barcodeImage: { width: 250, height: 90 },
  text: { fontSize: 12, marginBottom: 8, lineHeight: 1.5 },
  label: { color: '#555' },
  footer: { position: 'absolute', bottom: 40, left: 0, right: 0, textAlign: 'center', fontSize: 10, color: '#888' }
});

const BarcodePDF = ({ assignment, barcodeDataUrl, user }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Assignment Submission Barcode Sheet</Text>
      
      <View style={styles.section}>
        <Text style={styles.text}><Text style={styles.label}>Student Name: </Text>{user?.fullName || assignment.studentId?.fullName}</Text>
        <Text style={styles.text}><Text style={styles.label}>Registration No: </Text>{user?.regdNo || assignment.studentId?.regdNo}</Text>
        <Text style={styles.text}><Text style={styles.label}>Subject: </Text>{assignment.groupSubjectName || assignment.subjectId?.subName}</Text>
        <Text style={styles.text}><Text style={styles.label}>Subject Code: </Text>{assignment.subjectId?.subCode}</Text>
        <Text style={styles.text}><Text style={styles.label}>Required Pages: </Text>{assignment.pagesRequired}</Text>
      </View>

      <View style={styles.barcodeContainer}>
        <Image src={barcodeDataUrl} style={styles.barcodeImage} />
        <Text style={{ fontSize: 11, marginTop: 15, color: '#444' }}>Please attach this sheet securely to the front of your completed activity record.</Text>
      </View>

      <Text style={styles.footer}>Generated by AKNU Digital Evaluation System</Text>
    </Page>
  </Document>
);

export default BarcodePDF;
